CREATE TABLE vic (
  DATA_DATE VARCHAR(30) NOT NULL,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASED FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT
	
	
);

SELECT * FROM vic;


CREATE TABLE act (
  DATA_DATE VARCHAR(30) NOT NULL,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASED FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT
);
CREATE TABLE nsw (
  DATA_DATE VARCHAR(30) NOT NULL,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASED FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT
	
);

CREATE TABLE qld (
  DATA_DATE VARCHAR(30) NOT NULL,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASED FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT
	
	
);


CREATE TABLE nt (
  DATA_DATE VARCHAR(30) NOT NULL,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASED FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT		
);
CREATE TABLE wa (
  DATA_DATE VARCHAR(30) NOT NULL,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASED FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT		
);
CREATE TABLE sa (
  DATA_DATE VARCHAR(30) NOT NULL,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASED FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT		
);
CREATE TABLE tas (
  DATA_DATE VARCHAR(30) NOT NULL,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASED FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT		
);

