DROP TABLE IF EXISTS vic;
DROP TABLE IF EXISTS act;
DROP TABLE IF EXISTS nsw;
DROP TABLE IF EXISTS qld;
DROP TABLE IF EXISTS sa;
DROP TABLE IF EXISTS tas;
DROP TABLE IF EXISTS nt;
DROP TABLE IF EXISTS wa;
CREATE TABLE vic (
  DAT DATE,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASES FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT
	
	
);

SELECT * FROM vic;


CREATE TABLE act (
  DAT date,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASES FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT
);

SELECT * FROM act;
CREATE TABLE nsw (
  DAT date,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASES FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT
	
);
SELECT * FROM nsw;
CREATE TABLE qld (
  DAT date,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASES FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT
	
	
);
SELECT * FROM qld;

CREATE TABLE nt (
  DAT date,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASES FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT		
);
SELECT * FROM nt;
CREATE TABLE wa (
  DAT date,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASES FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT		
);
SELECT * FROM wa;
CREATE TABLE sa (
  DAT date,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASES FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT		
);
SELECT * FROM sa;
CREATE TABLE tas (
  DAT date,
  HOSP FLOAT,
  ICU  FLOAT,
  VENT FLOAT,
  NEW_CASES FLOAT,
CURRENT_CASES FLOAT,
	DEATHS FLOAT,
	NEW_RAT_CASES FLOAT,
	CURRENT_RAT_CASES FLOAT		
);
SELECT * FROM tas;
